version: '3'

services:
  frontend:
    image: igregory/time-app-frontend-dev
    restart: always
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - '3000:3000'
  api:
    image: igregory/time-app-api-dev
    restart: always
    depends_on:
      - mysql
    volumes:
      - /app/node_modules
      - ./api:/app
    ports:
      - '5555:5000'
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PORT: '3306'
      MYSQL_PASSWORD: password
      MYSQL_DB: time_db
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
    volumes:
      - mysql_data_pub:/var/lib/mysql
  adminer:
    restart: always
    image: adminer
    ports:
      - '8888:8080'
volumes:
    mysql_data_pub:
